<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kavenegar" Version="1.2.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Visit.BLL\Visit.BLL.csproj" />
    <ProjectReference Include="..\Visit.Shared\Visit.Shared.csproj" />
  </ItemGroup>

</Project>
